name: checks

on: [pull_request]
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2

      - name: Checkout mage
        uses: actions/checkout@v2
        with:
          repository: magefile/mage
          path: mage

      - name: Install mage
        run: |
          cd mage
          mkdir -p "$(go env GOPATH)"
          go run bootstrap.go

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$(go env GOPATH)/bin" latest

      - name: Run checks
        run: |
          export PATH="${PATH}:$(go env GOPATH)/bin"
          mage check
